[package]
name = "file-browser-with-benefits-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.5"
image = "0.24.7"
image-base64 = "0.1.0"
opener = "0.6.1"
rocket = { version = "0.5.0", features = ["secrets"] }
serde_json = "1.0.108"
